<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */

return array (
    'Remain good friends with the customer'=>'',
    'Release Date'=>'',
    'Author\'s support of the project and the client'=>'',
    'Project'=>'',
    'Design assignment (formed on the basis of the customer\'s wishes'=>'',
    'Meeting the client'=>'',
	'ABOUT COMPANY' => '',
	'About the company' => '',
	'Address' => '',
	'BELIEVE' => '',
	'CONTACTS' => '',
	'Close' => '',
	'Contact us' => '',
	'Do you want site like this?' => '',
	'Email' => '',
	'Follow us' => '',
	'GALLERY' => '',
	'Gallery' => '',
	'HOME' => '',
	'Home222' => '',
	'Keep the good relationship with the client' => '',
	'MAKE AN ORDER' => '',
	'Name' => '',
	'No data received' => '',
	'PARTNERS' => '',
	'PRINCIPLES' => '',
	'Page not found' => '',
	'Principles of operation' => '',
	'Send' => '',
	'Tel.' => '',
	'Thanks' => '',
	'The requested page does not exist.' => '',
	'You Email' => '',
	'You Message' => '',
	'You Name' => '',
	'and immediately' => '',
	'back to gallery' => '',
	'close' => '',
	'professionals' => '',
	'style' => '',
	'we will contact with you' => '',
	'Do you have a question for us?' => '@@@@',
	'Your email' => '@@@@',
	'Your mail' => '@@@@',
	'Your message' => '@@@@',
	'Your name' => '@@@@',
);
